# Generated by Django 4.2.4 on 2023-08-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
